version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: nihonggo
      POSTGRES_PASSWORD: nihonggo123
      POSTGRES_DB: nihonggo_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: nextjs-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://nihonggo:nihonggo123@db:5432/nihonggo_db
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]

volumes:
  db_data:
